# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Finiup Mag' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Finiup Mag
  pod 'OneSignal', '>= 2.5.2', '< 3.0'

end

target 'OneSignalNotificationServiceExtension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OneSignalNotificationServiceExtension
  pod 'OneSignal', '>= 2.5.2', '< 3.0'

end
