# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'Zizz' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Zizz
  pod 'OneSignal', '>= 2.6.2', '< 3.0'

end


target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
end