# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '0bc.xyz' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 0bc.xyz
  pod 'OneSignal', '>= 2.5.2', '< 3.0'

end

target 'XpressShare' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XpressShare

end

target 'OneSignalNotificationServiceExtension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OneSignalNotificationServiceExtension
  pod 'OneSignal', '>= 2.5.2', '< 3.0'
end
